In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv(r'data\1_homeprices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
model = LinearRegression()
model.fit(df[['area']], df['price'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [4]:
model.coef_

array([135.78767123])

In [5]:
model.intercept_

180616.43835616432

In [6]:
model.predict([[5000]])

array([859554.79452055])

# 1. `pickle`

In [7]:
import pickle

### Saving trained model using `pickle`

Python's `pickle` module allows us to save Python objects to _.pickle_ files.

In [8]:
# Opeining a file in 'write bytes' mode
with open('model_pickle', 'wb') as file:
    pickle.dump(model, file)

### Opening "pickled" model from file

In [9]:
# Opeining a file in 'read bytes' mode
with open('model_pickle', 'rb') as file:
    mp = pickle.load(file)

### Using the trained model loaded from file

In [10]:
mp.predict([[5000]])

array([859554.79452055])

In [11]:
mp.coef_

array([135.78767123])

In [12]:
mp.intercept_

180616.43835616432

# 2. `joblib`

`from sklearn.externals import joblib` has been depricated.

`joblib` can now be directly imported, if installed via pip or conda.

In [13]:
import joblib

### Saving trained model using `joblib`

Scikit-learn's `joblib` module allows us to save trained models, especially ones with a large number of Numpy arrays much more efficiently.

In [14]:
joblib.dump(model, 'model_joblib')

['model_joblib']

### Opening trained model from `joblib` file

In [15]:
mj = joblib.load('model_joblib')

### Using the trained model loaded from file

In [16]:
mj.predict([[5000]])

array([859554.79452055])

In [17]:
mj.coef_

array([135.78767123])

In [18]:
mj.intercept_

180616.43835616432